api_version = "2023-10"

[[extensions]]
handle = "test-eos-payment-customization"
name = "t:name"
description = "t:description"
type = "function"

  [[extensions.targeting]]
  target = "purchase.payment-customization.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"

[extensions.input.variables]
namespace = "$app:test-eos-payment-customization"
key = "function-configuration"