# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-eos-payment-customization"
client_id = "fe2aa32404dc24d79e156da465ff8c96"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_payment_customizations,read_payment_customizations"

[auth] 
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "eos-test-development.myshopify.com"
